language: php

php:
  - 7

before_script:
  - composer self-update
  - composer install

script: ./vendor/bin/phpunit tests/

matrix:
  fast_finish: true

notifications:
  on_success: never
  on_failure: never
