language: php

php:
  - nightly

before_script:
#  - composer self-update
  - composer install

script: phpunit tests/

matrix:
  fast_finish: true

notifications:
  on_success: never
  on_failure: always
